language: node_js
before_script:
  - npm install -g gatsby-cli
node_js:
  - '10'
deploy:
  provider: script
  script:
    - npm ci && npm run deploy
    - echo "skipping tests"
  skip_cleanup: true
  on:
    branch: master
