name = "piyushmehta-com"
main = "dist/_worker.js"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist"
binding = "ASSETS"

[env.production]
name = "piyushmehta-com"

[env.preview]
name = "piyushmehta-com-preview"
