name = "piyushmehta-com"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[assets]
directory = "./dist"

[env.production]
NODE_ENV = "production"

[placement]
mode = "smart"
